/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARate: typeof import('ant-design-vue/es')['Rate']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ChooseArea: typeof import('./src/components/ChooseArea/index.vue')['default']
    ChooseCity: typeof import('./src/components/ChooseCity/index.vue')['default']
    ChooseData: typeof import('./src/components/ChooseData/index.vue')['default']
    ChooseDate: typeof import('./src/components/ChooseDate/index.vue')['default']
    ChooseIcon: typeof import('./src/components/ChooseIcon/index.vue')['default']
    ChooseTime: typeof import('./src/components/ChooseTime/index.vue')['default']
    DialogForm: typeof import('./src/components/DialogForm/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElIconBell: typeof import('@element-plus/icons-vue')['Bell']
    ElIconCirclecheck: typeof import('@element-plus/icons-vue')['Circlecheck']
    ElIconCircleCheck: typeof import('@element-plus/icons-vue')['CircleCheck']
    ElIconConnection: typeof import('@element-plus/icons-vue')['Connection']
    ElIconElementplus: typeof import('@element-plus/icons-vue')['Elementplus']
    ElIconElementPlus: typeof import('@element-plus/icons-vue')['ElementPlus']
    ElIconExpand: typeof import('@element-plus/icons-vue')['Expand']
    ElIconFold: typeof import('@element-plus/icons-vue')['Fold']
    ElIconMenu: typeof import('@element-plus/icons-vue')['Menu']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    ElTimeSelect: typeof import('element-plus/es')['ElTimeSelect']
    FullCalendar: typeof import('./src/components/FullCalendar/index.vue')['default']
    ModalForm: typeof import('./src/components/ModalForm/index.vue')['default']
    ModalTable: typeof import('./src/components/ModalTable/index.vue')['default']
    NavHeader: typeof import('./src/components/NavHeader/index.vue')['default']
    NavSide: typeof import('./src/components/NavSide/index.vue')['default']
    Notification: typeof import('./src/components/Notification/index.vue')['default']
    Pagination: typeof import('./src/components/Pagination/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
