/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChooseArea: typeof import('./src/components/ChooseArea/index.vue')['default']
    ChooseCity: typeof import('./src/components/ChooseCity/index.vue')['default']
    ChooseIcon: typeof import('./src/components/ChooseIcon/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIconApple: typeof import('@element-plus/icons-vue')['Apple']
    ElIconBell: typeof import('@element-plus/icons-vue')['Bell']
    ElIconEdit: typeof import('@element-plus/icons-vue')['Edit']
    ElIconExpand: typeof import('@element-plus/icons-vue')['Expand']
    ElIconFold: typeof import('@element-plus/icons-vue')['Fold']
    ElIconMenu: typeof import('@element-plus/icons-vue')['Menu']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    MessageList: typeof import('./src/components/MessageList/index.vue')['default']
    NavHeader: typeof import('./src/components/NavHeader/index.vue')['default']
    NavSide: typeof import('./src/components/NavSide/index.vue')['default']
    Notification: typeof import('./src/components/Notification/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
